export const APP_CONSTANTS = {
    HIDE_DELAY: 1000,
    SHOW_DELAY: 300,
    CURSOR_OFFSET_X: 10,
    CURSOR_OFFSET_Y: -30,
    SMALL_SIZE: 30,
    FULL_WIDTH: 300,
    FULL_HEIGHT: 100,
    MIN_DISTANCE_TO_MOVE: 300,
    SCROLL_THROTTLE_TIME: 100,
};

export const ANIMATION_DURATIONS = {
    POPUP_EXPAND: 300,
    POPUP_SHRINK: 300,
    POPUP_MOVEMENT: 300,
    BACKGROUND_BLUR: 500,
};

export const DEFAULT_SETTINGS = {
    WORDS_PER_MINUTE: 400,
    MIN_WORDS: 10,
    TEXT_SIZE: 24,
};

